import logging

import requests
from django import forms
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import URLValidator
from django.utils import timezone
from django.utils.html import format_html
from django.utils.translation import gettext_lazy as _

from governanceplatform.validators import validate_external_https_url

from .base import (
    BaseConnector,
    DeliveryResult,
    NotificationContext,
    PermanentDeliveryError,
    TransientDeliveryError,
)
from .registry import register

logger = logging.getLogger(__name__)

REQUEST_TIMEOUT = 10


class RTConfigForm(forms.Form):
    url = forms.URLField(
        label=_("URL"),
        help_text="e.g., https://rt.example.com",
        validators=[URLValidator(), validate_external_https_url],
        assume_scheme="https",
    )
    queue = forms.CharField(label=_("Queue"), max_length=255)


@register
class RTConnector(BaseConnector):
    type_id = "rt"
    label = _("RT (Request Tracker)")
    config_form = RTConfigForm
    requires_secret = True
    secret_label = _("Token")

    def _base_url(self):
        return self.connector.config.get("url", "").rstrip("/")

    def _headers(self):
        return {
            "Content-Type": "application/json",
            "Accept": "application/json",
            "Authorization": f"token {self.connector.secret}",
        }

    def send(self, ctx: NotificationContext) -> DeliveryResult:
        base_url = self._base_url()
        try:
            validate_external_https_url(base_url)
        except ValidationError:
            raise PermanentDeliveryError(str(_("The RT URL is not allowed")))

        if ctx.previous_external_ref:
            url = f"{base_url}/REST/2.0/ticket/{ctx.previous_external_ref}/correspond"
            payload = {
                "Content": ctx.content_html,
                "ContentType": "text/html",
            }
        else:
            url = f"{base_url}/REST/2.0/ticket"
            payload = {
                "Requestor": settings.EMAIL_SENDER,
                "Queue": self.connector.config.get("queue", ""),
                "Subject": ctx.subject,
                "Content": ctx.content_html,
                "ContentType": "text/html",
            }

        try:
            response = requests.post(url, json=payload, headers=self._headers(), timeout=REQUEST_TIMEOUT)
        except requests.RequestException as e:
            # raw exception to the log for debugging, friendly message to the user
            logger.error("Error connecting to RT API: %s", e)
            raise TransientDeliveryError(str(_("Error connecting to RT API")))

        if response.ok:
            external_ref = ctx.previous_external_ref
            if not ctx.previous_external_ref and response.status_code == 201:
                external_ref = str(response.json().get("id", ""))
            return DeliveryResult(success=True, external_ref=external_ref)

        logger.error("RT API error %s: %s", response.status_code, response.text)
        if response.status_code == 401:
            raise PermanentDeliveryError(str(_("RT token unauthorized (401)")))
        if response.status_code == 404:
            raise PermanentDeliveryError(str(_("RT queue not found (404)")))
        if response.status_code >= 500:
            raise TransientDeliveryError(str(_("RT server error (%s)")) % response.status_code)

        # other 4xx (e.g. 403): surface RT's own message, which is human-readable and actionable
        detail = self._rt_error_detail(response)
        message = str(_("RT API error (%s)")) % response.status_code
        if detail:
            message = f"{message}: {detail}"
        raise PermanentDeliveryError(message)

    @staticmethod
    def _rt_error_detail(response) -> str:
        try:
            data = response.json()
        except ValueError:
            return ""
        if isinstance(data, dict):
            return data.get("message", "")
        if isinstance(data, list) and data and isinstance(data[0], dict):
            return data[0].get("message", "")
        return ""

    def test_connection(self) -> tuple[bool, str]:
        config = self.connector.config
        if not config.get("url") or not config.get("queue") or not self.connector.secret:
            return False, str(_("RT configuration is incomplete"))

        generated_at = timezone.now().strftime("%Y-%m-%d %H:%M %Z")
        ctx = NotificationContext(
            incident=None,
            subject=f"[TEST] SERIMA - RT connection ({generated_at})",
            content_html=format_html(
                "<p>This is an automated test ticket generated by SERIMA to verify the RT API connection.</p>"
                "<p><strong>This ticket can be safely deleted.</strong></p>"
                "<hr>"
                "<p>Observer: {}</p>"
                "<p>Queue: {}</p>"
                "<p>Generated at: {}</p>",
                str(self.connector.observer),
                config["queue"],
                generated_at,
            ),
        )
        try:
            result = self.send(ctx)
        except (TransientDeliveryError, PermanentDeliveryError) as e:
            return False, str(e)

        if result.external_ref:
            return True, str(_("Connection successful — test ticket #%s created")) % result.external_ref
        return True, str(_("Connection successful"))
