Contact
-------

- `NC3 Luxembourg <https://www.nc3.lu>`_ - `info@nc3.lu <info@nc3.lu>`_
- `ILR <https://web.ilr.lu>`_ - `serima@ilr.lu <serima@ilr.lu>`_

License
-------

The Governance Platform is licensed under
`GNU Affero General Public License version 3 <https://www.gnu.org/licenses/agpl-3.0.html>`_.

- Copyright (C) 2023-2026 Juan Rocha <juan.rocha@nc3.lu>
- Copyright (C) 2023-2026 Jérôme Lombardi <jerome.lombardi@nc3.lu>
- Copyright (C) 2023-2026 Cédric Bonhomme <cedric.bonhomme@nc3.lu>
- Copyright (C) 2023-2026 Ruslan Baidan <ruslan.baidan@nc3.lu>
- Copyright (C) 2023-2026 `NC3 Luxembourg <https://www.nc3.lu>`_
