# Generated by Django 6.0.5 on 2026-05-20 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0021_alter_assetdatatranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedreport',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_report', to='reporting.project', verbose_name='Project'),
        ),
    ]
