# Generated by Django 6.0.5 on 2026-05-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0022_alter_generatedreport_project'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='riskdata',
            constraint=models.UniqueConstraint(fields=('uuid', 'service'), name='unique_risk_uuid_service'),
        ),
    ]
