# Generated by Django 6.0.6 on 2026-06-11 11:52

from django.db import migrations
from django.db.models import Q


def remove_null_translations(apps, schema_editor):
    models = [
        (apps.get_model('securityobjectives', 'DomainTranslation'), 'label'),
        (apps.get_model('securityobjectives', 'MaturityLevelTranslation'), 'label'),
        (apps.get_model('securityobjectives', 'StandardTranslation'), 'label'),
        (apps.get_model('securityobjectives', 'SecurityObjectiveTranslation'), 'objective'),
    ]

    fallback_language = "en"

    for model, field in models:
        missing_q = Q(**{f"{field}__isnull": True}) | Q(**{f"{field}": ""})

        for translation in model.objects.filter(missing_q):
            fallback = (
                model.objects.filter(
                    master_id=translation.master_id,
                    language_code=fallback_language,
                )
                .exclude(**{f"{field}__isnull": True})
                .exclude(**{f"{field}": ""})
                .first()
            )

            if fallback:
                value = getattr(fallback, field)
            else:
                value = f"[Missing {field} ({translation.language_code})]"

            setattr(translation, field, value)
            translation.save(update_fields=[field])


class Migration(migrations.Migration):

    dependencies = [
        ('securityobjectives', '0034_alter_domain_id_alter_domaintranslation_id_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_null_translations),
    ]
