# Generated by Django 6.0.6 on 2026-06-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityobjectives', '0035_remove_null_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaintranslation',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='maturityleveltranslation',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='securityobjectivetranslation',
            name='objective',
            field=models.CharField(max_length=255, verbose_name='Objective'),
        ),
        migrations.AlterField(
            model_name='standardtranslation',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='standardtranslation',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Label'),
        ),
    ]
