# Generated by Django 6.0.6 on 2026-06-11 13:17

from django.db import migrations
from django.db.models import Q


def fix_unique_code(apps, schema_editor):
    SecurityObjective = apps.get_model("securityobjectives", "SecurityObjective")

    missing = Q(unique_code__isnull=True) | Q(unique_code="")

    for obj in SecurityObjective.objects.filter(missing):
        creator_part = obj.creator_id or "SYSTEM"
        obj.unique_code = f"SO_{obj.pk}{creator_part}{obj.domain_id}"
        obj.save(update_fields=["unique_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('securityobjectives', '0036_alter_domaintranslation_label_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_unique_code),
    ]
