# Generated by Django 6.0.6 on 2026-06-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityobjectives', '0037_fix_unique_code_if_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityobjective',
            name='unique_code',
            field=models.CharField(max_length=255, verbose_name='Unique code'),
        ),
    ]
