# Generated by Django 6.0.6 on 2026-07-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityobjectives', '0039_add_regulatoradmin_rights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityobjectivestatus',
            name='status',
            field=models.CharField(choices=[('NOT_REVIEWED', 'Not reviewed'), ('PASS', 'Passed'), ('FAIL', 'Revision required')], default='NOT_REVIEWED', verbose_name='Status'),
        ),
    ]
