# Generated by Django 6.0.8 on 2026-08-19 12:38

from django.db import migrations, models
from django.db.models import Count, Min


def keep_oldest_duplicate(apps, schema_editor):
    database_alias = schema_editor.connection.alias
    models_and_related_fields = (
        ("SecurityMeasureAnswer", "security_measure_id"),
        ("SecurityObjectiveStatus", "security_objective_id"),
    )

    for model_name, related_field in models_and_related_fields:
        model = apps.get_model("securityobjectives", model_name)
        manager = model.objects.using(database_alias)
        duplicate_groups = (
            manager.exclude(standard_answer_id=None)
            .exclude(**{related_field: None})
            .values("standard_answer_id", related_field)
            .annotate(keep_id=Min("id"), row_count=Count("id"))
            .filter(row_count__gt=1)
        )

        for duplicate_group in duplicate_groups:
            manager.filter(
                standard_answer_id=duplicate_group["standard_answer_id"],
                **{related_field: duplicate_group[related_field]},
            ).exclude(pk=duplicate_group["keep_id"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("securityobjectives", "0040_alter_securityobjectivestatus_status"),
    ]

    operations = [
        migrations.RunPython(keep_oldest_duplicate, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="securitymeasureanswer",
            constraint=models.UniqueConstraint(fields=("standard_answer", "security_measure"), name="uniq_measure_answer_per_declaration"),
        ),
        migrations.AddConstraint(
            model_name="securityobjectivestatus",
            constraint=models.UniqueConstraint(
                fields=("standard_answer", "security_objective"), name="uniq_objective_status_per_declaration"
            ),
        ),
    ]
