# Generated by Django 6.1.1 on 2026-09-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityobjectives', '0041_deduplicate_answers_and_add_unique_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='actions_mandatory',
            field=models.BooleanField(default=True, verbose_name='Mandatory'),
        ),
        migrations.AddField(
            model_name='standard',
            name='justification_mandatory',
            field=models.BooleanField(default=True, verbose_name='Mandatory'),
        ),
        migrations.AddField(
            model_name='standard',
            name='score_display',
            field=models.CharField(choices=[('FULL', 'Score and maximum'), ('SCORE', 'Score only'), ('NONE', 'Hidden')], default='FULL', max_length=5, verbose_name='Score'),
        ),
        migrations.AddField(
            model_name='standard',
            name='show_actions',
            field=models.BooleanField(default=True, verbose_name='Show'),
        ),
        migrations.AddField(
            model_name='standard',
            name='show_evidence_column',
            field=models.BooleanField(default=True, verbose_name='Show'),
        ),
        migrations.AddField(
            model_name='standard',
            name='show_justification_column',
            field=models.BooleanField(default=True, verbose_name='Show'),
        ),
        migrations.AddField(
            model_name='standard',
            name='show_maturity_level_column',
            field=models.BooleanField(default=True, verbose_name='Show'),
        ),
        migrations.AddField(
            model_name='standard',
            name='show_review_comment_column',
            field=models.BooleanField(default=True, verbose_name='Show'),
        ),
        migrations.AddField(
            model_name='standardtranslation',
            name='actions_label',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Planned Measures label'),
        ),
        migrations.AddField(
            model_name='standardtranslation',
            name='evidence_label',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Evidence label'),
        ),
        migrations.AddField(
            model_name='standardtranslation',
            name='is_implemented_label',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Measure Implemented? label'),
        ),
        migrations.AddField(
            model_name='standardtranslation',
            name='justification_label',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Justification label'),
        ),
        migrations.AddField(
            model_name='standardtranslation',
            name='maturity_level_label',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Maturity Level label'),
        ),
        migrations.AddField(
            model_name='standardtranslation',
            name='review_comment_label',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Review Comment label'),
        ),
        migrations.AddField(
            model_name='standardtranslation',
            name='security_measure_label',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Security Measure label'),
        ),
    ]
