# Generated by Django 6.1.1 on 2026-09-15 11:59

import securityobjectives.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityobjectives', '0042_standard_actions_mandatory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardanswergroup',
            name='group_id',
            field=models.CharField(default=securityobjectives.models.generate_standard_answer_group_id, max_length=39, unique=True, verbose_name='Group ID'),
        ),
    ]
