# Generated by Django 6.1.1 on 2026-09-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityobjectives', '0043_alter_standardanswergroup_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
