# Generated by Django 6.1.1 on 2026-09-23 09:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanceplatform', '0066_regulatoruser_can_export_security_objectives'),
        ('securityobjectives', '0044_standard_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityObjectiveExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='uuid')),
                ('filename', models.CharField(max_length=255, verbose_name='Filename')),
                ('task_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Task id')),
                ('task_status', models.CharField(choices=[('RUNNING', 'Running'), ('DONE', 'Successful'), ('FAIL', 'Failed')], default='RUNNING', max_length=10, verbose_name='Status')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('regulation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='governanceplatform.regulation', verbose_name='Regulation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Security objective export',
                'verbose_name_plural': 'Security objective exports',
            },
        ),
    ]
