# Generated by Django 6.0.5 on 2026-05-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanceplatform', '0060_alter_entitycategorytranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observerregulation',
            name='sectors',
            field=models.ManyToManyField(blank=True, to='governanceplatform.sector', verbose_name='Sectors'),
        ),
    ]
