# Generated by Django 6.1.1 on 2026-09-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanceplatform', '0065_alter_company_country_alter_observer_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulatoruser',
            name='can_export_security_objectives',
            field=models.BooleanField(default=False, verbose_name='Can export security objectives'),
        ),
    ]
