# Generated by Django 6.1.1 on 2026-09-25 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0066_regulatoruser_can_export_security_objectives"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="observer",
            name="is_receiving_all_incident",
        ),
    ]
