# Generated by Django 6.0.6 on 2026-07-08 14:16

from django.db import migrations, models


def allow_existing_connector_types(apps, schema_editor):
    Observer = apps.get_model("governanceplatform", "Observer")
    ObserverConnector = apps.get_model("governanceplatform", "ObserverConnector")
    for observer in Observer.objects.all():
        types = sorted(
            set(ObserverConnector.objects.filter(observer=observer).values_list("connector_type", flat=True))
        )
        if types:
            observer.allowed_connector_types = types
            observer.save(update_fields=["allowed_connector_types"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('governanceplatform', '0067_remove_observer__rt_token_remove_observer_rt_queue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observer',
            name='allowed_connector_types',
            field=models.JSONField(blank=True, default=list, verbose_name='Available connectors'),
        ),
        migrations.RunPython(allow_existing_connector_types, noop),
    ]
