# Generated by Django 6.1.1 on 2026-10-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('governanceplatform', '0067_remove_observer_is_receiving_all_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionality',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='functionalities', to='auth.group', verbose_name='Roles'),
        ),
    ]
