# Generated by Django 6.0.6 on 2026-06-16 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanceplatform', '0064_alter_applicationconfig_id_alter_company_id_and_more'),
        ('incidents', '0061_alter_answer_id_alter_email_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoptions',
            name='is_conditional',
            field=models.BooleanField(default=False, verbose_name='Conditional display'),
        ),
        migrations.AddField(
            model_name='questionoptionshistory',
            name='is_conditional',
            field=models.BooleanField(default=False, verbose_name='Conditional display'),
        ),
        migrations.CreateModel(
            name='ConditionalQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Creator name')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='governanceplatform.regulator', verbose_name='Creator')),
                ('next_question_options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditional_targets', to='incidents.questionoptions', verbose_name='Next question')),
                ('predefined_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditional_questions', to='incidents.predefinedanswer', verbose_name='Selected answer')),
                ('question_options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditional_triggers', to='incidents.questionoptions', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Conditional question',
                'verbose_name_plural': 'Conditional questions',
                'constraints': [models.UniqueConstraint(fields=('question_options', 'predefined_answer'), name='Unique_ConditionalQuestionOption_per_answer')],
            },
        ),
    ]
