# Generated by Django 6.0.6 on 2026-06-18 08:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0062_questionoptions_is_conditional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionalquestionoption',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conditionalquestionoption',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deleted at'),
        ),
        migrations.CreateModel(
            name='ConditionalQuestionOptionsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('question_options_id', models.IntegerField()),
                ('predefined_answer_id', models.IntegerField()),
                ('next_question_options_id', models.IntegerField()),
                ('question_options_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditional_maps', to='incidents.questionoptionshistory')),
            ],
        ),
    ]
