# Generated by Django 6.0.6 on 2026-06-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0063_conditionalquestionoption_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='company_name',
            field=models.CharField(max_length=100, verbose_name='Legal Entity Name'),
        ),
    ]
