# Generated by Django 6.0.6 on 2026-07-07 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanceplatform', '0065_observerconnector'),
        ('incidents', '0064_alter_incident_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_ref', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10, verbose_name='Status')),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='governanceplatform.observerconnector', verbose_name='Connector')),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.email', verbose_name='Email template')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_deliveries', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'Connector delivery',
                'verbose_name_plural': 'Connector deliveries',
                'indexes': [models.Index(fields=['incident', 'connector', 'status'], name='incidents_c_inciden_727abc_idx')],
            },
        ),
    ]
