# Generated by Django 6.1 on 2026-08-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0064_alter_incident_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtranslation',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
    ]
