# Generated by Django 6.0.6 on 2026-07-07 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0066_migrate_rttickets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RTTicket',
        ),
    ]
