# Generated by Django 6.1.1 on 2026-09-15 09:57

import incidents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0068_renumber_duplicate_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_id',
            field=models.CharField(default=incidents.models.generate_incident_reference, max_length=28, unique=True, verbose_name='Incident Reference'),
        ),
    ]
